name: RecreatorLib
version: ${version}
main: com.fembuncollective.recreatorlib.RecreatorLib
api-version: '1.21'
author: MissAnilka
description: ${description}
load: STARTUP

# Optional dependencies - features will be enabled if these plugins are present
softdepend:
  - floodgate
